### ISSUE TITLE
better handling of yaml config, including from cli

### ISSUE THREAD

**Issue by amitschang** [ssec-jhu/dplutils#64]
There is a way to get config from yaml in executor, but there is no hookup in the cli utils. Also, the current config does not also deal with context, which feels awkward. we might want something like:

```yaml
---
context:
  ctxvar: someval
  ctxarr:
  - 1
  - 2
taskconfig:
  task:
     kwargs: ...
```

qualifying it like this opens up possibility of pipelines defined entirely in yaml, where the task graph and executor also set there.
